[package]
name = "mongo-connection-check"
version = "0.8.5"
authors = ["Paul Done <pkdone@gmail.com>"]
edition = "2018"

[dependencies]
futures = { version = "0.3.*"}
tokio = {version = "0.2.*", features = ["full"] }
lazy_static = "1.4.*"
regex = "1"
domain = "0.5.*"
trust-dns-resolver = "0.19.*"
clap = "2.33.*"
mongodb = "1.1.*"
